### ISSUE TITLE
Warning. Administración.RegistroDeUsuarios.

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#1]
### Administración.RegistroDeUsuarios. Warn.
Comando de **Suprimir/Retirar** no existe. Solo se puede inactivar un usuario. **Para suprimir/retirar habría que hacerlo por SQL.**

**Comment by repositorio-2020** [comment]
Una vez creado los usuarios en la plataforma, no se debe eliminar de la base de datos. Lo que se hace es in activarlo. En las bases de datos transaccionales no se elimina información se inactiva con el fin de mantener la integridad de la información de bases de datos y mantener las relaciones.
