### ISSUE TITLE
09. Menú Archivo.Perfiles: No hay comando Nuevo. 

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#10]
Menú Archivo.Perfiles: No hay comando Nuevo. Cómo se incluyen nuevos perfiles?.

**Comment by repositorio-2020** [comment]
Desde el aplicativo no se incluye solo se consulta. Cada perfil se especifica en las historias y se definen sus características de acceso a las funciones las cuales se activan y se asocian los filtros correspondientes.
