### ISSUE TITLE
10. Menú Archivo.Administracion.Estudiante: Comando Leer.

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#11]
Menú Archivo.Administracion.Estudiante: Comando Leer. Deja estado “Modificar” como si permietiese este comando (acción) pero
![EC-10-Menú Archivo Administracion](https://user-images.githubusercontent.com/29695114/78367418-abb4a980-7587-11ea-9ac8-5546729083bd.jpg)
 no es posible.

**Comment by repositorio-2020** [comment]
Lo actualice y lo deje de igual forma para estudiantes, curso y perfil. Como se ve en la gráfica de estudiantes:

![image](https://user-images.githubusercontent.com/61713006/79405673-a9285b80-7f5a-11ea-9675-435cea35adc3.png)
