### ISSUE TITLE
11. Menú Archivo.Administracion.Cusos: Comando Leer. 

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#12]
Menú Archivo.Administracion.Cusos: Comando Leer. 
![EC-11-Menú Archivo Administracion 2](https://user-images.githubusercontent.com/29695114/78367676-16fe7b80-7588-11ea-9664-e09557ac9a0c.jpg)
Cuando se digita en el campo código un   valor, no encuentra el registro correspondiente, aun cuando este exista.
--

**Comment by repositorio-2020** [comment]
Efectué la prueba busque por el código y me funciono ademas cuando consultaba colocaba el Valor Modificar y lo Cambie de la misma forma que la opción de perfil, este cambio lo efectue tambien para estudiantes. Como se ve en la gráfica:
1. Seleccionar registro por codigo - Ingreso Codigo 100:
![image](https://user-images.githubusercontent.com/61713006/79405443-08d23700-7f5a-11ea-8e2d-1f2539963adc.png)


2. Consultado por el codigo 100 y trae el detalle del curso:
![image](https://user-images.githubusercontent.com/61713006/79405493-27d0c900-7f5a-11ea-8774-2d3f6dbfa39b.png)
