### ISSUE TITLE
12. General de Submenú Administración

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#13]
1. REVISAR FORMATOS DE CAMPOS I.E. Fechas
2. REVISAR CONSISTENCIAS Fech. Final > Fech. Inicial
3. REVISAR INTEGRIDAD .  I. E:   Suprimir Universidad donde hay Calendarios. Suprimir Registros Activos en   [Casi] Todas las pantallas.

**Comment by repositorio-2020** [comment]
Se maneja la integridad con listas asociadas a las tablas de parametros asi asegurar la integridad de las tablas transaccionales con las tablas de parametros
