### ISSUE TITLE
13. La Clave de usuario no está siendo encriptada.

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#14]
[RF 1.13]. La   Clave de usuario no está siendo encriptada.

**Comment by repositorio-2020** [comment]
Solucionado: La clave ahora es almacenada en la base de datos encriptada con MD5. Este valor se actualiza en los siguientes casos:
1. Cuando se crea el usuario en la base de datos.
2. Cuando el usuario cambia la clave.
3. Cuando ingresa el usuario la clave esta se encripta y se compara con el valor en base de datos.
De acuerdo a lo anterior la única persona que sabe la clave es el usuario.
