### ISSUE TITLE
14. El usuario podrá cambiar el Estado del registro de usuario de Activo a Inactivo

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#15]
Particularmente, el usuario podrá cambiar el Estado del registro de usuario de Activo a Inactivo o Viceversa [RF 1.14]. El viceversa no es posible.

**Comment by repositorio-2020** [comment]
Revise el cambio de estado de Activo a Inactivo y de Inactivo a Activo. Funciono correctamente el cambio de estado sin problema y verifique en la base de datos y el cambio se llevo a cabo. El procedimiento aplicado es el siguiente:
1. Seleccione  de la grilla de usuarios el registro a modificar dando click en la lupa.
2. En la parte superior selecciono de la lista el estado Activo o Inactivo.
3. Luego selecciono el botón Guardar y este confirma el salvado en la base de datos.
4. Luego del cambio entro de nuevo a la opción y se evidencia el cambio de estado.
