### ISSUE TITLE
15. Los perfiles solo permiten consultar,  no se puede modificar o crear.

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#16]
[RF 1.12]. Los perfiles solo permiten consultar,  no se puede modificar o crear.

**Comment by repositorio-2020** [comment]
Efectivamente allí no se pueden crear mas perfiles. Si se definen mas perfiles estos y las opciones a las que tienen acceso se especifican y se configuran internamente.
