### ISSUE TITLE
18. Tableros de Control de BI

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#18]
Cuando se selecciona alguno, no despliega los tableros de control de Power BI

**Comment by repositorio-2020** [comment]
Revise el tema directamente en el servidor de la UNAD. Existe un bloqueo en el explorador que no permite el despliegue de las gráficas de BI. En la siguiente gráfica se evidencia el bloqueo al ingresar a los tableros.

![image](https://user-images.githubusercontent.com/61713006/84453894-a37b8900-ac1e-11ea-8245-4f7f17e5d828.png)
