### ISSUE TITLE
19. Modelos. Al leer con código inexistente no da error

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#19]
En la pantalla de definición de modelos, al leer con código inexistente, no da error
[Issue 19X Modleos. Al leer con codigo inexstente no da error.docx](https://github.com/repositorio-2020/PublicaIndicadores/files/4770415/Issue.19X.Modleos.Al.leer.con.codigo.inexstente.no.da.error.docx)

**Comment by repositorio-2020** [comment]
Se implementa el filtro por código y lo verifica si no cumple no trae información. Efectué la prueba filtrando por código 9999 y no consulto nada de información. En la gráfica se evidencia que indica que no trae información

![image](https://user-images.githubusercontent.com/61713006/86395132-5f9c0280-bc65-11ea-9262-dc26940ebe89.png)
