### ISSUE TITLE
01-EC-Administracion.Estudiante.

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#2]
La pantalla sólo deja leer estudiantes dado que ellos son cargados de los LOgs y no deben dejarse modificar. Sin embargo, Al consultarlos muestra la leyenda "Modificar", lo cual tiende a confundir como si se pudiera modificar  aun cuando la funcionalidad no lo permite.
![EC-AdministracionEstudiante-01](https://user-images.githubusercontent.com/29695114/76663650-a26b8a80-654f-11ea-947d-01a1fb101dd7.JPG)

**Comment by repositorio-2020** [comment]
Se ajusta la opción de estudiantes.  Al momento de leer se cambio el estado de Modificar a Consultado como se evidencia en la gráfica.


![image](https://user-images.githubusercontent.com/61713006/79403011-3c5d9300-7f53-11ea-8106-66bf0bdc0fa1.png)
