### ISSUE TITLE
20. Menu Consulta-Reportes Dos opciones de prueba a eliminar.

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#20]
Al final del menu hay dos opciones que son de Prueba Power BI y deben ser eliminadas.

[Issue 20X - Menu Consulta-Reportes Dos opicones de prueba a eliminar.docx](https://github.com/repositorio-2020/PublicaIndicadores/files/4770423/Issue.20X.-.Menu.Consulta-Reportes.Dos.opicones.de.prueba.a.eliminar.docx)

**Comment by repositorio-2020** [comment]
Se dispone de acceso a 4 tipos de tableros de gráficas en BI. Si se requiere mas se deben especificar para adicionarlos en el menú.


![image](https://user-images.githubusercontent.com/61713006/86403735-e22bbe80-bc73-11ea-9144-5581ef466b61.png)
