### ISSUE TITLE
21. General menu de Consulta/Reportes.

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#21]
General menú de Consulta/Reportes. en todas las pantallas se debe estandarizar el nombre del botón <Limpiar Filtro> por <Cancelar>

**Comment by repositorio-2020** [comment]
Se estandariza el botón a Cancelar en las opciones de Gráficas y Reportes


![image](https://user-images.githubusercontent.com/61713006/86420874-8b3adf00-bc9d-11ea-98f0-4b73d77e2dd9.png)

![image](https://user-images.githubusercontent.com/61713006/86420914-adccf800-bc9d-11ea-8fcb-b45291f7d2e1.png)
