### ISSUE TITLE
22. Pant Ppal Logo

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#22]
[Issue 22 - Pant Ppal Logo.docx](https://github.com/repositorio-2020/PublicaIndicadores/files/4863847/Issue.22.-.Pant.Ppal.Logo.docx)
Logo principal se corta

**Comment by repositorio-2020** [comment]
El logo se carga en la pantalla principal y lo puse en el atributo TOP del logo. Quitando el atributo Center del logo de esa forma queda en la parte superior evitando que quede cortado el logo.


![image](https://user-images.githubusercontent.com/61713006/86406267-6bdd8b00-bc78-11ea-8237-b35394a045af.png)
