### ISSUE TITLE
23. Pant Ppal Frame DB

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#23]
[Issue 23 - Pant Ppal Frame DB.docx](https://github.com/repositorio-2020/PublicaIndicadores/files/4863854/Issue.23.-.Pant.Ppal.Frame.DB.docx)
Ver si es possible extender el Frame del DB para que cubra el mayor area de pantalla posible.

**Comment by repositorio-2020** [comment]
Se extiende al maximo la interfaces de BI. como se observa en la grafica.


![image](https://user-images.githubusercontent.com/61713006/86421845-f6d27b80-bca0-11ea-806c-bda029906b2b.png)
