### ISSUE TITLE
24. Pant Ppal Menu distante

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#24]
[Issue 24 - Pant Ppal Menu distante.docx](https://github.com/repositorio-2020/PublicaIndicadores/files/4863891/Issue.24.-.Pant.Ppal.Menu.distante.docx)
Corregir, el menu desplegable queda muy perdido. Se pierde...

**Comment by repositorio-2020** [comment]
Para evitar que el menu se pierda al llamar a BI. Entonces se cambio el menú a un bar menú. De esta forma este se mentiene siempre en la parte superior. También se aumento el tablero en donde se despliega la interfaces de BI. Ver grafica 

![image](https://user-images.githubusercontent.com/61713006/86421694-9d6a4c80-bca0-11ea-9f33-03983405469e.png)
