### ISSUE TITLE
25. Pant Ppal La pantalla de la opción debería cubrir toda la pantalla

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#25]
[Issue 25 - Pant Ppal La pantalla de la opción debería cubrir toda la pantalla.docx](https://github.com/repositorio-2020/PublicaIndicadores/files/4863903/Issue.25.-.Pant.Ppal.La.pantalla.de.la.opcion.deberia.cubrir.toda.la.pantalla.docx)
La pantalla de la opción debería cubrir toda la pantalla

**Comment by repositorio-2020** [comment]
Le puse color gris en la parte inferior para que no quede tan blanco. Sin embargo la parte vacía se llena en el momento que se leen los datos, como se observa en la grafica

![image](https://user-images.githubusercontent.com/61713006/86421389-7e1eef80-bc9f-11ea-8de3-8d2b67050abc.png)


![image](https://user-images.githubusercontent.com/61713006/86421424-9e4eae80-bc9f-11ea-849d-65d891232fcd.png)
