### ISSUE TITLE
26. Pant Ppal Volver a Original

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#26]
[Issue 26 - Pant Ppal Volver a Original.docx](https://github.com/repositorio-2020/PublicaIndicadores/files/4863905/Issue.26.-.Pant.Ppal.Volver.a.Original.docx)
No retorna a la presentacion original de la pantalla

**Comment by repositorio-2020** [comment]
El menú se cambio y se mantiene en la barra superior sin afectar al llamar a Power BI. Como se ve en la gráfica. Cuando se selecciona una opción normal retorna a las condiciones normales del menú y el escritorio de ELA, como se observa en la gráfica.

![image](https://user-images.githubusercontent.com/61713006/86421056-3350a800-bc9e-11ea-8926-1805f325d55d.png)

![image](https://user-images.githubusercontent.com/61713006/86421110-685cfa80-bc9e-11ea-9632-22981c1ae487.png)
