### ISSUE TITLE
27. Menú Gráfica Indicadores - Ortografía

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#27]
[Issue 27. Menu Grafica Indicadores - Ortografia.docx](https://github.com/repositorio-2020/PublicaIndicadores/files/4865016/Issue.27.Menu.Grafica.Indicadores.-.Ortografia.docx)

Verificar Ortografía de Menú y puntos. Ver puntos y correcciones.

**Comment by repositorio-2020** [comment]
Se corrige la organización ortografía y el menú se ajusta como una barra ademas de corregir cada una de las opciones como se ve en las gráficas


![image](https://user-images.githubusercontent.com/61713006/86418670-845c9e00-bc96-11ea-8561-74c877047990.png)

![image](https://user-images.githubusercontent.com/61713006/86418873-3300de80-bc97-11ea-9d86-345e674a624a.png)
