### ISSUE TITLE
28. Pruebas UTADEO. Carga.

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#28]
En las pruebas de performance el aplicativo se comporta como se espera, sin embargo empiezan a fallar cuando  sin previo aviso el servidor se cae, que es frecuentemente.
![image](https://user-images.githubusercontent.com/29695114/88199988-1e1ac980-cc0b-11ea-90cc-95837ecd0c02.png)

**Comment by repositorio-2020** [comment]
Durante la semana en la que se realizaron pruebas, el servidor fue desconectado razón por la cual se genero el error reportado. Una vez me comentaron del error revise el servidor y efectivamente los servicios se encontraban abajo.
