### ISSUE TITLE
29. Pruebas UTADEO. Diseño.

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#29]
La página de inicio cuenta con poco diseño, provocando vacíos en la pantalla.
![image](https://user-images.githubusercontent.com/29695114/88200098-4d313b00-cc0b-11ea-91c3-d18d8f24fccf.png)

**Comment by repositorio-2020** [comment]
Se cambio la pantalla inicial como se puede ver en la grafica, a solicitud de la UNAD.
![image](https://user-images.githubusercontent.com/61713006/97790750-46667c80-1b99-11eb-90e1-772ad45bbeaa.png)
