### ISSUE TITLE
30. Pruebas UTADEO. Seguridad (Sugerencia de prueba).

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#30]
Las credenciales no cuenta con indicativos para la creación de contraseña segura.
![image](https://user-images.githubusercontent.com/29695114/88200229-7fdb3380-cc0b-11ea-9047-fef7ee713f8f.png)

**Comment by repositorio-2020** [comment]
Referente a este punto no existe un requerimiento funcional en el que se especifique las características del password. Sin embargo al momento de actualizar o definir el password se le indica al usuario el nivel de seguridad de su password como se evidencia en la gráfica a continuación:
![image](https://user-images.githubusercontent.com/61713006/89240146-ddcf2a00-d5c0-11ea-8774-a82bbc06d30a.png)


![image](https://user-images.githubusercontent.com/61713006/89240164-efb0cd00-d5c0-11ea-9862-2659fde3ced9.png)

![image](https://user-images.githubusercontent.com/61713006/89240187-00f9d980-d5c1-11ea-882c-fad284072d11.png)
