### ISSUE TITLE
34. Perfiles. Funcionalidad código perfil. 

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#34]
(0031) REPROBADA.

Descripción: Verificar que al ingresar el numero “1”en codigo de   perfil y de click en leer, me muestre el perfil designado.
--
Pasos de   prueba:    ingresar exitosamente al aplicativo   2. Navegar por la pantalla de las   propiedades    3. Dar click en archivo   4. Dar clic en perfiles

**Comment by repositorio-2020** [comment]
Se ha implementado el filtro de búsqueda por código. En la gráfica a continuación se ingresa el código para leer y así filtrar la información, como se observa en la gráfica  a continuación:
![image](https://user-images.githubusercontent.com/61713006/89790854-2c605500-dae8-11ea-832a-db7e6327db13.png)


Luego seleccionamos el botón Leer y trae la información de ese perfil de acuerdo al código del perfil. Se puede observar en la gráfica a continuación:

![image](https://user-images.githubusercontent.com/61713006/89791040-616ca780-dae8-11ea-91c2-44f76af94743.png)
