### ISSUE TITLE
35. Perfiles. Funcionalidad código perfil

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#35]
(0032) REROBADA.

Descripción: Verificar que al ingresar el numero “2”en codigo de   perfil y de click en leer, me muestre el perfil designado.
--
Pasos de   prueba:    ingresar exitosamente al aplicativo   2. Navegar por la pantalla de las   propiedades    3. Dar click en archivo   4. Dar clic en perfiles

**Comment by repositorio-2020** [comment]
Se ha implementado el filtro por código de perfil. La explicación detallada fue realizada en la incidencia 34. Que describía el mismo caso con el código 1. Anexo gráfica en donde se filtra en este caso para el código 2.

![image](https://user-images.githubusercontent.com/61713006/89791414-ebb50b80-dae8-11ea-9f27-5061dabfc75a.png)
