### ISSUE TITLE
36. Módulo: perfiles. Funcionalidad nombre perfil.

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#36]
(0033) REPROBADA:

Descripción: Verificar que al ingresar    “administrador”en nombre de perfil y de click en leer, me muestre el   perfil designado.
--
Pasos de   prueba:    ingresar exitosamente al aplicativo   2. Navegar por la pantalla de las   propiedades    3. Dar click en archivo   4. Dar clic en perfiles

**Comment by repositorio-2020** [comment]
Se ingresa el nombre Administrador y filtra por ese texto.  Como se evidencia en la gráfica
![image](https://user-images.githubusercontent.com/61713006/89792087-b5c45700-dae9-11ea-8b46-30525a016fb5.png)


Se consulta y el resultado se ve a continuación en la gráfica como resultado de la lectura
![image](https://user-images.githubusercontent.com/61713006/89792197-d42a5280-dae9-11ea-86d9-b258428317ea.png)
