### ISSUE TITLE
37. Perfiles. Funcionalidad nombre perfil.

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#37]
(0034) REPROBADO.

Descripción: Verificar que al ingresar    “consultas”en nombre de perfil y de click en leer, me muestre el perfil   designado.
--
Pasos de   prueba:    ingresar exitosamente al aplicativo   2. Navegar por la pantalla de las   propiedades    3. Dar click en archivo   4. Dar clic en perfiles

**Comment by repositorio-2020** [comment]
Se implemento el filtro por nombre en el perfil y al filtrar y leer muestra la información filtrada esta incidencia esta relacionada con la 36. Ver gráfica a continuación

![image](https://user-images.githubusercontent.com/61713006/89792468-3420f900-daea-11ea-854a-dba199bced5b.png)
