### ISSUE TITLE
38. Pantalla de universidad. Funcionalidad de crear una nueva universidad.

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#38]
(042) REPROBADO.

Descripción: Verificar la   funcionalidad al escribir un nuevo código, universidad y un estado y dar clic   en nuevo y  validar
--
Pasos de   prueba:    1. Ingresar exitosamente al   aplicativo   2. Navegar por la pantalla de las   propiedades    3. Dar clic en administración   4. Dar clic en universidad

**Comment by repositorio-2020** [comment]
Se revisa y prueba este proceso y se ajusto para que cuando se ingrese la información y luego se de nuevo, el sistema elimine los datos en la ventana y quede dispuesta para capturar los datos ya que esta en blanco para un nuevo registro.

![image](https://user-images.githubusercontent.com/61713006/89796646-8284c680-daef-11ea-9db2-b4850b50eda6.png)

Después de ingresar algunos datos se selecciona nuevo y deja los campos en blanco y se puede proceder a la captura del nuevo registro. 
![image](https://user-images.githubusercontent.com/61713006/89798468-d690aa80-daf1-11ea-9191-4d3e34add785.png)
