### ISSUE TITLE
39. Pantalla de definición de curso. Probar la caja de texto.

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#39]
(0062) REPROBADO.

Descripción: Verificar que al ingresar el texto correspondiente a la   descripción y dar clic en leer, valide.
--
Pasos de   prueba:    1. Ingresar exitosamente al   aplicativo   2. Navegar por la pantalla de las   propiedades    3. Dar clic en administración   4. Dar clic en Curso

**Comment by repositorio-2020** [comment]
Esta ventana no se le implementa validaciones ya que no permite modificar ni adicionar información. Solo es de consulta.
