### ISSUE TITLE
40. Pantalla de definición de curso. Probar scroll de universidad.

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#40]
(0064) REPROBADA. 

Descripción: Verificar que al dar clic en la universidad uno y dar   clic en leer, valide.
--
Pasos de   prueba:    1. Ingresar exitosamente al   aplicativo   2. Navegar por la pantalla de las   propiedades    3. Dar clic en administración   4. Dar clic en Curso

**Comment by repositorio-2020** [comment]
Muestra las universidades definidas en la opción de universidades la lista funciona correctamente, como se muestra en la gráfica a continuación:

![image](https://user-images.githubusercontent.com/61713006/89801268-8ae00000-daf5-11ea-8187-425298066661.png)
