### ISSUE TITLE
41. Pantalla de definición de curso. Pobar scroll de universidad.

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#41]
(0066) REPROBADA.

Descripción: Verificar que al dar clic en la universidad tres y dar   clic en leer, valide.
--
Pasos de   prueba:    1. Ingresar exitosamente al   aplicativo   2. Navegar por la pantalla de las   propiedades    3. Dar clic en administración   4. Dar clic en Curso

**Comment by repositorio-2020** [comment]
Se filtra y lee por la lista de la universidad seleccionada. Como se evidencia en las graficas a continuacion:
![image](https://user-images.githubusercontent.com/61713006/89801924-5f114a00-daf6-11ea-815c-a8d882013593.png)

Luego se lee y no trae ningún dato por ese tipo de universidad
![image](https://user-images.githubusercontent.com/61713006/89802028-8831da80-daf6-11ea-811c-552cb0f42456.png)

Si le pongo otro filtro que si tenga universidad asociada si sale la información
![image](https://user-images.githubusercontent.com/61713006/89802130-ab5c8a00-daf6-11ea-9240-017bb59e72e5.png)

Sale la siguiente información

![image](https://user-images.githubusercontent.com/61713006/89802173-c29b7780-daf6-11ea-9125-391200e1aba1.png)
