### ISSUE TITLE
42. Pantalla de Calendario Académico. Probar la caja de texto.

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#42]
(0076) REPROBADA.

Descripción: Verificar que al ingresar el texto correspondiente en Fch   inicial  y dar clic en leer, valide.
--
Pasos de   prueba:    1. Ingresar exitosamente al   aplicativo   2. Navegar por la pantalla de las   propiedades    3. Dar clic en administración   4. Dar clic en Calendario

**Comment by repositorio-2020** [comment]
Filtros por las fechas no fueron implementados. Solo se implemento por los codigos y las listas de valores.
