### ISSUE TITLE
43. Pantalla de Calendario Académico.  probar scroll universidad.

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#43]
(0078) REPROBADA.

Descripción: Verificar que al seleccionar la universidad uno y dar   clic en leer, valide.
--
Pasos de   prueba:    1. Ingresar exitosamente al   aplicativo   2. Navegar por la pantalla de las   propiedades    3. Dar clic en administración   4. Dar clic en Calendario

**Comment by repositorio-2020** [comment]
Se selecciona la universidad filtra y si tiene información de lo contrario indica que la información no fue encontrada, como se ve en la gráfica a continuación
![image](https://user-images.githubusercontent.com/61713006/89802726-7a308980-daf7-11ea-8d91-96dc20d7164f.png)
