### ISSUE TITLE
44. Pantalla de Calendario Académico. Probar la caja de texto.

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#44]
(0079) REPROBADO.

Descripción: Verificar que al ingresar el texto correspondiente en   Fch. Final  y dar clic en leer, valide.
--
Pasos de   prueba:    1. Ingresar exitosamente al   aplicativo   2. Navegar por la pantalla de las   propiedades    3. Dar clic en administración   4. Dar clic en Calendario---

**Comment by repositorio-2020** [comment]
Por el atributo de caja de texto se verifica la longitud pero no es posible realizar el filtro por el texto o parte de este.
