### ISSUE TITLE
45. Pantalla de Calendario Académico. probar scroll universidad

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#45]
(0081) REPROBADO.

Descripción: Verificar que al seleccionar la universidad tres y dar   clic en leer, valide.
--
Pasos de   prueba:    1. Ingresar exitosamente al   aplicativo   2. Navegar por la pantalla de las   propiedades    3. Dar clic en administración   4. Dar clic en Calendario

**Comment by repositorio-2020** [comment]
Se accede a la pantalla de calendario academico y se despliega la lista de las universidades y despliega correctamente. Ademas por este atributo se pueden filtrar la informacion de los calendarios academicos
![image](https://user-images.githubusercontent.com/61713006/97790679-93961e80-1b98-11eb-88e4-f61b988cd0a8.png)
