### ISSUE TITLE
46. Pantalla de Definición de Indicadores. Probar la caja de texto.

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#46]
(0096) REPROBADO.

Descripción: Verificar que al ingresar el texto correspondiente en   código equivale y dar clic en leer, valide.
--
Pasos de   prueba:    1. Ingresar exitosamente al   aplicativo   2. Navegar por la pantalla de las   propiedades    3. Dar clic en administración   4. Dar clic en Indicador

**Comment by repositorio-2020** [comment]
Por la descripción no se realiza busquedas. Ya que es un texto descriptivo. Se busca por valores especificos como el codigo y de algunos de los parametros de listas.
