### ISSUE TITLE
47. Pantalla de Definición de Indicadores. Probar la caja de texto.

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#47]
(0097) REPROBADO.

Descripción: Verificar que al ingresar el texto correspondiente en   Descripción y dar clic en leer, valide.
--
Pasos de   prueba:    1. Ingresar exitosamente al   aplicativo   2. Navegar por la pantalla de las   propiedades    3. Dar clic en administración   4. Dar clic en Indicador

**Comment by repositorio-2020** [comment]
Es importante indicar que el aplicativo no realiza búsquedas por la descripción ni completa ni parcial. Si desea buscar lo debe hacer por el código del indicador.
