### ISSUE TITLE
48. Pantalla de Definición de Indicadores. Probar la funcionalidad del scroll de Cobertura

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#48]
(0103) REPROBADO.

Descripción: Verificar que al seleccionar Curso en el scroll de   cobertura y de clic en leer, valide.
--
Pasos de   prueba:    1. Ingresar exitosamente al aplicativo   2. Navegar por la pantalla de las   propiedades    3. Dar clic en administración   4. Dar clic en Indicador

**Comment by repositorio-2020** [comment]
Se filtra por cobertura y funciona. muestra en la grafica que se filtra por la cobertura que no existe y muestra el error que no fue encontrados registros.

![image](https://user-images.githubusercontent.com/61713006/97790631-12d72280-1b98-11eb-8876-a82b1e7ede8c.png)
