### ISSUE TITLE
49. Pantalla de Definición de Indicadores. probar la funcionalidad del scroll de Cobertura.

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#49]
(0103) REPROBADO.

Descripción: Verificar que al seleccionar Curso en el scroll de   cobertura y de clic en leer, valide.
--
Pasos de   prueba:    1. Ingresar exitosamente al aplicativo   2. Navegar por la pantalla de las   propiedades    3. Dar clic en administración   4. Dar clic en Indicador

**Comment by repositorio-2020** [comment]
Se realiza el filtro por el campo de ci¿obertura y funciona correctamente. Filtra y consulta la informacion de todos los registros con este atributo seleccionado:
![image](https://user-images.githubusercontent.com/61713006/97790402-71030600-1b96-11eb-9d4e-8a18ec5fad32.png)

Tener en cuenta que indicadores de curso no hay. Solo hay indicadores a nivel de estudiante.

![image](https://user-images.githubusercontent.com/61713006/97790423-8aa44d80-1b96-11eb-81ea-5bf54604bba5.png)
