### ISSUE TITLE
04. Menú Archivo.Registro Usuario.Nuevo: Al ingresar campos nuevos...

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#5]
![EC-04-Menu Archivo Registro Usuario NUevo](https://user-images.githubusercontent.com/29695114/78366744-90956a00-7586-11ea-8fd6-42fbdae37b11.jpg)
Menú Archivo.Registro Usuario.Nuevo: Al ingresar campos nuevos validos en todos,  y dar Guardar , aparece “No records found” y no aparece el nuevo registro en amarillo.

**Comment by repositorio-2020** [comment]
Se ajusta el software y se realiza la prueba como evidencia se toma las siguientes graficas asociadas al procedimiento de adicionar un usuario:
1.  Adicionar un nuevo usuario.
![image](https://user-images.githubusercontent.com/61713006/82400155-4411cb00-9a1c-11ea-98bd-d230e60423ed.png)


2. Guardar la adición del nuevo registro. Se envía confirmación. Importante una vez confirmada la adicion del nuevo registro. se lee y aparece en la lista el registro.
![image](https://user-images.githubusercontent.com/61713006/82400292-8fc47480-9a1c-11ea-806d-88aa99ef403d.png)
