### ISSUE TITLE
50. Pantalla de Definición de Indicadores. Probar la funcionalidad del scroll de Tipo de periodo

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#50]
105.  REPROBADO.

Descripción: Verificar que al seleccionar mensual en el scroll de tipo   de periodo y de clic en leer, valide.
--
Pasos de   prueba:    1. Ingresar exitosamente al   aplicativo   2. Navegar por la pantalla de las   propiedades    3. Dar clic en administración   4. Dar clic en Indicador

**Comment by repositorio-2020** [comment]
Filtra por el campo tipo de periodo. Aunque la periodicidad de los indicadores para este proyecto es semanal. Se puede ver en la gráfica la evidencia que filtra y por este tipo de periodo no encuentra resultados.

![image](https://user-images.githubusercontent.com/61713006/89803293-3b4f0380-daf8-11ea-8b89-ba861e0d1a97.png)
