### ISSUE TITLE
51. Pantalla de Definición de Indicadores. Probar la funcionalidad de botón nuevo.

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#51]
(0111) REPROBADA.

Descripción: Verificar que al ingresar los datos correspondientes   menos una casilla y al  dar clic en   nuevo, salga aviso de incompatibilidad
--
Pasos de   prueba:    1. Ingresar exitosamente al   aplicativo   2. Navegar por la pantalla de las   propiedades    3. Dar clic en administración   4. Dar clic en Indicador

**Comment by repositorio-2020** [comment]
Se realiza la operacion de adicionar y valida la informacion obligaoria. Evitando asi posibles errores de no tener toda la informacion completa. se puede ver las validaciones de los atributos en esta primera parte.
![image](https://user-images.githubusercontent.com/61713006/97790348-fa660880-1b95-11eb-9322-2a081d95ca65.png)


Ahora una vez registrado el registro se adiciona en la base de datos. como se puede ver a continuacion:

![image](https://user-images.githubusercontent.com/61713006/97790365-2ed9c480-1b96-11eb-826b-337cda9bc1fd.png)
