### ISSUE TITLE
52. Pantalla de Log. Proceso. Probar la funcionalidad de botón Limpiar filtro

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#52]
(0122) REPROBADO.

Descripción: Verificar que al    dar click en leer, valide.
--
Pasos de   prueba:    1. Ingresar exitosamente al   aplicativo   2. Navegar por la pantalla de las   propiedades    3. Dar clic en administración   4. Dar clic en Log. Proceso

**Comment by repositorio-2020** [comment]
Esta opción solo permite consultar el log de los últimos 500 movimientos generados en el procesamiento de la información. Aquí no hay opción para filtrar la información del log.
