### ISSUE TITLE
57. Pantalla de Modelos. Funcionalidad de scroll de estado.

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#57]
(0141) REPROBADO. 

Descripción: Verificar que al seleccionar la opción modelo matemático   dos en el scroll de Modelo general y dar clic en leer, valide.
--
Pasos de   prueba:    1. Ingresar exitosamente al   aplicativo   2. Navegar por la pantalla de las   propiedades    3. Dar clic en modelos   4. Dar clic en Modelos grupo

**Comment by repositorio-2020** [comment]
Se selecciona el codigo del estado como filtro, y se efectua la busqueda, para lo cual efectivamente si filtra y consulta los registros por el estado seleccionado. Para el caso de este ejemplo se selecciono el estado activo, Ver grafica a continuacion

![image](https://user-images.githubusercontent.com/61713006/97791867-32c11300-1ba5-11eb-86f5-abe3389ac849.png)
