### ISSUE TITLE
05. Menú Archivo.CambiarClave. Donde se definen y cuales son las políticas de claves?

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#6]

**Comment by repositorio-2020** [comment]
Referente a este punto no existe un requerimiento funcional en el que se especifique las características del password. Sin embargo al momento de actualizar o definir el password se le indica al usuario el nivel de seguridad de su password como se evidencia en la gráfica a continuación:
![image](https://user-images.githubusercontent.com/61713006/89240432-aa40cf80-d5c1-11ea-99af-ef6e146c5c3f.png)

![image](https://user-images.githubusercontent.com/61713006/89240455-b62c9180-d5c1-11ea-91db-7c77b09e5668.png)

![image](https://user-images.githubusercontent.com/61713006/89240469-c3498080-d5c1-11ea-9ca4-5d0f37e5e71e.png)
