### ISSUE TITLE
60. Pantalla de Modelos. Funcionalidad del botón cancelar.

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#60]
(0151)  REPROBADO.

Descripción:  verificar que al   escribir el texto correspondiente en código interno y dar clic en cancelar ,   valide.
--
Pasos de   prueba:    1. Ingresar exitosamente al   aplicativo   2. Navegar por la pantalla de las   propiedades    3. Dar clic en modelos   4. Dar clic en Modelos grupo

**Comment by repositorio-2020** [comment]
El boton de cancelar al ser seleccionado limpia la informacion de todos los atributos dejando la opcion para el proceso de lectura. Se puede evidenciar este comportamiento en la siguiente grafica

![image](https://user-images.githubusercontent.com/61713006/97790895-bde8db80-1b9a-11eb-8b47-83196ce9a86f.png)
