### ISSUE TITLE
66. Pantalla de Modelos. Funcionalidad de botón de nuevo.

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#66]
(0172) REPROBADO.

Descripción: Verificar que al llenar los respectivos espacios menos   modelo   y dar clic en nuevo,lance   aviso de incompatibilidad..
--
Pasos de   prueba:    1. Ingresar exitosamente al   aplicativo   2. Navegar por la pantalla de las   propiedades    3. Dar clic en modelos   4. Dar clic en Modelo

**Comment by repositorio-2020** [comment]
No es claro la incidencia. Sin embargo los pasos para adicionar un nuevo registro son los siguientes:
1. Seleccionar el botón Nuevo.
2. Cada uno de los atributos quedan en blanco 
3. El usuario debe ingresar esta información en cada uno de los campos.
4. Cuando da Guardar el sistema valida y si hay error los muestra.
5. Si no existe errores almacena la información en la base de datos y termina el proceso.
