### ISSUE TITLE
06. Menú Archivo.Perfiles: El botón LimpiarFiltro ...

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#7]
06. Menú Archivo.Perfiles: El botón LimpiarFiltro debería llamarse Cancelar y Leer debería ser el más a la izquierda para guardar consistencia co
![EC-06-Menú Archivo Perfiles](https://user-images.githubusercontent.com/29695114/78366686-7bb8d680-7586-11ea-9ecd-f3279928b29f.jpg)
n las demás pantallas.

**Comment by repositorio-2020** [comment]
Se estandariza el botón de Limpiar Filtro a Cancelar como están las otras opciones del aplicativo.

![image](https://user-images.githubusercontent.com/61713006/79523081-fa9c1d80-8022-11ea-9fb5-59bc26c96f61.png)
