### ISSUE TITLE
73. Pantalla de Modelos. Funcionalidad de scroll de Modelo general

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#73]
(0184) REPROBADO.

Descripción: Verificar que al seleccionar la opción modelo matemático   uno en el scroll modelo general  y dar   clic en leer, valide.
--
Pasos de   prueba:    1. Ingresar exitosamente al   aplicativo   2. Navegar por la pantalla de las   propiedades    3. Dar clic en modelos   4. Dar clic en Resultado modelo

**Comment by repositorio-2020** [comment]
La especificación no es clara. Sin embargo se realiza el filtrado del modelo y lectura lo cual efectúa de manera correcta. En la gráfica a continuación se evidencia los resultados de la lectura filtrada.

![image](https://user-images.githubusercontent.com/61713006/90082871-89b9f900-dcd6-11ea-8a74-6d6abcaaedc2.png)
