### ISSUE TITLE
74. Pantalla de Modelos. Funcionalidad de scroll de Modelo general.

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#74]
(0185) REPROBADO.

Descripción: Verificar que al seleccionar la opción modelo matemático   uno en el scroll modelo general  y dar   clic en leer, valide.
--
Pasos de   prueba:    1. Ingresar exitosamente al   aplicativo   2. Navegar por la pantalla de las   propiedades    3. Dar clic en modelos   4. Dar clic en Resultado modelo

**Comment by repositorio-2020** [comment]
No es clara la especificación de la incidencia. Sin embargo se filtra por el modelo matemático y se lee, los resultados se evidencian en la gráfica a continuación:

![image](https://user-images.githubusercontent.com/61713006/90082770-45c6f400-dcd6-11ea-875b-9f4f2e813952.png)
