### ISSUE TITLE
75. Pantalla de Modelos. Funcionalidad de scroll de Modelo general.

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#75]
(0186) REPROBADO.

Descripción: Verificar que al seleccionar la opción modelo matemático   tres en el scroll modelo general  y dar   clic en leer, valide.
--
Pasos de   prueba:    1. Ingresar exitosamente al   aplicativo   2. Navegar por la pantalla de las   propiedades    3. Dar clic en modelos   4. Dar clic en Resultado modelo

**Comment by repositorio-2020** [comment]
La especificación de la incidencia no es clara. Sin embargo se filtra y se lee la información por la lista del modelo matemático. En la gráfica se puede ver la gráfica con la información consultada y filtrando por el modelo matemático.

![image](https://user-images.githubusercontent.com/61713006/90082655-f7195a00-dcd5-11ea-84ac-39d8f156e1e0.png)
