### ISSUE TITLE
76. Pantalla de Modelos. Funcionalidad de botón leer.

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#76]
(0187) REPROBADO.

Descripción: Verificar que al dar clic en leer, valide.
--
Pasos de   prueba:    1. Ingresar exitosamente al   aplicativo   2. Navegar por la pantalla de las   propiedades    3. Dar clic en modelos   4. Dar clic en Resultado modelo

**Comment by repositorio-2020** [comment]
Dado que no es claro la especificación de la incidencia se prueba la lectura de la opción de modelo y verifica la funcionalidad es correcta.

Se deja en blanco los parámetros 
![image](https://user-images.githubusercontent.com/61713006/90082203-d8669380-dcd4-11ea-8903-1841e84ed9c2.png)


Luego se da el botón leer y trae la información sin problema alguno
![image](https://user-images.githubusercontent.com/61713006/90082292-faf8ac80-dcd4-11ea-909b-abc0cc0112bd.png)
