### ISSUE TITLE
77. Pantalla de Gráfica/Indicado. Funcionalidad caja de texto.

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#77]
(0195) REPROBADO.

Descripción: Verificar que al ingresar el texto correspondiente en   código Estudiante y dar clic en leer, valide.
--
Pasos de   prueba:    1. Ingresar exitosamente al   aplicativo   2. Navegar por la pantalla de las   propiedades    3. Dar clic en modelos   4. Dar clic en Gráfica/indicador

**Comment by repositorio-2020** [comment]
No es clara la descripción de la incidencia, no describe lo que esta pasando en el aplicativo como incidencia.
