### ISSUE TITLE
78. Pantalla de Gráfica/Indicado.  Funcionalidad boton leer.

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#78]
(0198) REPROBADO.

Descripción: Verificar que al dar clic en leer, valide.
--
Pasos de   prueba:    1. Ingresar exitosamente al aplicativo   2. Navegar por la pantalla de las   propiedades    3. Dar clic en modelos   4. Dar clic en Gráfica/indicador

**Comment by repositorio-2020** [comment]
No es clara la especificación de la incidencia, para proceder a su implementacion.
