### ISSUE TITLE
79. Pantalla de Gráfica/Indicado. Funcionalidad boton leer.

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#79]
(0199) REPROBADO.

Descripción: Verificar que al dar clic en leer, valide.
--
Pasos de   prueba:    1. Ingresar exitosamente al aplicativo   2. Navegar por la pantalla de las   propiedades    3. Dar clic en modelos   4. Dar clic en Gráfica/indicador

**Comment by repositorio-2020** [comment]
Se deben ingresar parámetros que filtran la información y luego se realiza la lectura, para traer la información y mostrar la información y generar los reportes y consultas. Se solicita ser mas específicos en la especificación de las incidencias.
