### ISSUE TITLE
07. Menú Archivo.Perfiles: El   comando Leer no funciona

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#8]
1)        Menú Archivo.Perfiles: El   comando Leer no funciona correctamente   puesto que al digitar un valor en <Codigo Perfil> y dar un valor   funciona como si se leyera en vacío. Es decir, trae todos los registros.
--

**Comment by repositorio-2020** [comment]
Se implementa el filtro por codigo del perfil de tal forma que se pueda acceder a un perfil en particular. Se prueba ingresndo filtro igual a 2 y muestra la informacion del filtro correspondiente como se ve en la grafica
![image](https://user-images.githubusercontent.com/61713006/97790799-bb39b680-1b99-11eb-9b42-3cfeb46ac45e.png)
