### ISSUE TITLE
80. Pantalla de Gráfica/Indicado. Funcionalidad botón cancelar.

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#80]
(0200) REPROBADO.

Descripción: Verificar que al dar un código indicador  y clic en cancelar, valide.
--
Pasos de   prueba:    1. Ingresar exitosamente al   aplicativo   2. Navegar por la pantalla de las   propiedades    3. Dar clic en modelos   4. Dar clic en Gráfica/indicador

**Comment by repositorio-2020** [comment]
La opción no es clara ya que en el tema de gráficas de indicador cuando doy cancelar elimina el valor de indicador y lo deja en blanco. Anexo las gráficas que así lo evidencian para la opción Gráfica/Indicador Detallado

![image](https://user-images.githubusercontent.com/61713006/89908012-018f0300-dbb3-11ea-8e36-fde1f25ebcc8.png)

Luego doy cancelar e inicializa para ingresar de nuevo los parámetros de búsqueda
![Uploading image.png…]()
