### ISSUE TITLE
85. Pantalla de Gráfica/Indicador. Funcionalidad botón cancelar

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#85]
(0244) REPROBADO.

Descripción: Verificar que al dar clic en la opción semana 35 del   scroll de periodo ,y de clic en cancelar    valide.
--
Pasos de prueba:    1. Ingresar exitosamente al   aplicativo   2. Navegar por la pantalla de las   propiedades    3. Dar clic en   Gráfica/indicador   4. Dar clic en Indicadores

**Comment by repositorio-2020** [comment]
Para esta opción se elimina el parámetro de numero de semana, ya que el propósito de cada una de las gráficas es poder observar el comportamiento de cada uno de los indicadores durante todo el periodo académico. Se puede observar el la gráfica

![image](https://user-images.githubusercontent.com/61713006/89851171-77fb1900-db51-11ea-92e7-aff5229f43f1.png)


Los resultados de las gráficas son como se observan a continuación desde la semana 33 a la 52

 
![image](https://user-images.githubusercontent.com/61713006/89851239-a0831300-db51-11ea-9362-cbc58d26ed8a.png)
