### ISSUE TITLE
08. Menú Archivo.Perfiles: El comando Limpiar filtro

### ISSUE THREAD

**Issue by mchavama** [repositorio-2020/PublicaIndicadores#9]
![EC-08-Menú Archivo Perfiles 2](https://user-images.githubusercontent.com/29695114/78367496-d0108600-7587-11ea-8c4e-416c64549556.jpg)
2)	Menú Archivo.Perfiles: El comando Limpiar filtro no funciona correctamente puesto que al digitarlo limpia los valores de los campos  <Codigo Perfil> y <Nombre Perfil> pero en la pantalla de resultados deja el segundo registro.

**Comment by repositorio-2020** [comment]
Al momento de cancelar o limpiar el filtro como se ve en la grafica efectivamente, la lista quedaba activa el segundo registro. Se reviso el programa fuente y se limpia la lista de tal forma que ya no aparece el segundo registro con informacion como se ve en la grafica.

![image](https://user-images.githubusercontent.com/61713006/79523803-8f534b00-8024-11ea-89ca-f798af9bf1e2.png)
